"use client";

import { FileText, MailIcon, Phone, PhoneCall } from "lucide-react";
import Link from "next/link";
import { BsWhatsapp } from "react-icons/bs";
import { useState } from "react";
import MouseCursor from "./MouseCursor";
import { collection, addDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";

export default function FloatingIcons() {
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    mobile: "",
    message: "",
  });
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(null);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setSuccess(null);

    try {
      // Add a new document with autogenerated ID in 'sideEnq' collection
      const docRef = await addDoc(collection(db, "sideEnq"), {
        name: formData.name,
        email: formData.email,
        mobile: formData.mobile,
        message: formData.message,
        timestamp: new Date(),
      });

      setSuccess("Message sent successfully!");
      setFormData({ name: "", email: "", mobile: "", message: "" });
    } catch (error) {
      console.log("Error adding document: ", error);
      setSuccess("Something went wrong. Try again.");
    }

    setLoading(false);
  };

  const [customCursorVisible, setCustomCursorVisible] = useState(true);

  return (
    <>
      <div>
        <MouseCursor visible={customCursorVisible} />

        <div className="w-[50px] fixed top-1/2 right-0 bg-white transform -translate-y-1/2 border-t border-l border-b border-[#e8e8e8] rounded-l-[10px] z-[10000]">
           <button
          onClick={() => setShowForm(true)}
          className="w-full md:w-[50px] h-[50px] flex items-center justify-center md:border-b md:border-[#e8e8e8] group"
          aria-label="Mail"
        >
          <MailIcon
            size={25}
            className="text-white md:text-black group-hover:text-gray-300"
          />
        </button>
        
       
          <Link
            href="tel:+1234567890"
            target="_blank"
            className="w-full md:w-[50px] h-[50px] flex items-center justify-center md:border-b md:border-[#e8e8e8] group"
            aria-label="Call Us"
          >
            <PhoneCall
              size={25}
              className="text-black md:text-black group-hover:text-gray-300"
            />
          </Link>
       

        
          <a
            href="https://wa.me/919876543210"
            target="_blank"
            rel="noopener noreferrer"
            className="w-full md:w-[50px] h-[50px] flex items-center justify-center md:rounded-bl-[10px] group"
            aria-label="WhatsApp"
          >
            <BsWhatsapp
              size={25}
              className="text-black md:text-black group-hover:text-gray-300"
            />
          </a>
        </div>
      </div>

      <div
        className={`fixed top-1/2 right-0 w-64 bg-slate-900 rounded-l-xl transform transition-transform duration-300 z-[10001]
  ${
    showForm ? "translate-x-0" : "translate-x-full"
  } -translate-y-1/2 cursor-auto`}
      >
        <div className="flex justify-between items-center p-3 border-b border-gray-700">
          <h2 className="text-lg font-bold text-white">Contact Us</h2>
          <button
            onClick={() => setShowForm(false)}
            className="text-gray-400 hover:text-white text-xl"
          >
            ✖
          </button>
        </div>

        <form
          onSubmit={handleSubmit}
          className="p-4 flex flex-col gap-3 cursor-auto"
        >
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleChange}
            placeholder="Your Name"
            required
            className="border border-gray-600 bg-slate-800 text-white p-2 rounded placeholder-gray-400"
          />
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            placeholder="Your Email"
            required
            className="border border-gray-600 bg-slate-800 text-white p-2 rounded placeholder-gray-400"
          />
          <input
            type="text"
            name="mobile"
            value={formData.mobile}
            onChange={handleChange}
            placeholder="Your Mobile"
            required
            className="border border-gray-600 bg-slate-800 text-white p-2 rounded placeholder-gray-400"
          />
          <textarea
            name="message"
            value={formData.message}
            onChange={handleChange}
            placeholder="Your Message"
            required
            rows="3"
            className="border border-gray-600 bg-slate-800 text-white p-2 rounded placeholder-gray-400"
          />
          <button
            type="submit"
            disabled={loading}
            className="bg-blue-900 text-white py-2 rounded hover:bg-blue-900"
          >
            {loading ? "Sending..." : "Submit"}
          </button>
          {success && <p className="text-sm text-green-400">{success}</p>}
        </form>
      </div>
    </>
  );
}
