export const products = [
  {
    slug: "hrms-suite",
    name: "HRMS Suite",
    tagline: "Mobile & Web Admin Dashboard",
    category: "HR & Workforce",
    tag: "Enterprise",
    gradient: "from-blue-600 to-cyan-500",
    description: "Complete Human Resource Management System with powerful mobile app and web admin dashboard. Manage employees, attendance, leaves, payroll, and performance — all in one unified platform built for enterprises of any scale.",
    longDescription: "Shrote's HRMS Suite is a comprehensive cloud-based Human Resource Management System designed for modern enterprises. Built with cutting-edge technology, it provides a unified platform to manage every aspect of your HR operations — from recruitment and onboarding to payroll processing and performance management. With both mobile and web admin dashboards, your HR team can access critical data and perform actions from anywhere, anytime.",
    features: ["Employee Onboarding", "Leave & Attendance", "Performance Review", "Role-based Access", "Payroll Integration", "Document Management", "Employee Self-Service Portal", "HR Analytics Dashboard"],
    benefits: ["Reduce HR manual work by 70%", "Real-time attendance & leave tracking", "Seamless payroll integration", "Mobile app for employees & managers", "Customizable workflows", "Compliance-ready reports"],
    techStack: ["React Native", "Next.js", "Node.js", "PostgreSQL", "Redis", "AWS"],
    keywords: "HRMS software India, HR management system, employee management software, attendance tracking system, payroll management system Bangalore",
  },
  {
    slug: "erp-suite",
    name: "ERP Suite",
    tagline: "End-to-End Enterprise Resource Planning",
    category: "Business Management",
    tag: "Enterprise",
    gradient: "from-violet-600 to-purple-500",
    description: "A powerful ERP suite designed for enterprises to streamline operations, manage supply chains, finances, procurement, and reporting within a single integrated ecosystem.",
    longDescription: "Shrote's ERP Suite is an enterprise-grade resource planning platform that connects every department of your business. From finance and accounting to supply chain and inventory — every process is integrated, automated, and optimized for maximum efficiency.",
    features: ["Finance Management", "Supply Chain", "Procurement Module", "Real-time Analytics", "Inventory Control", "CRM Integration", "Multi-branch Support", "Custom Reporting"],
    benefits: ["Unified business operations", "Real-time data visibility", "Reduce operational costs by 40%", "Scalable architecture", "Multi-currency support", "Automated workflows"],
    techStack: ["React", "Node.js", "MongoDB", "Microservices", "Docker", "AWS"],
    keywords: "ERP software India, enterprise resource planning, ERP suite Bangalore, business management software, ERP system for small business",
  },
  {
    slug: "e-commerce-application",
    name: "E-Commerce Application",
    tagline: "Next-Gen Online Retail Platform",
    category: "E-Commerce",
    tag: "Scalable",
    gradient: "from-orange-500 to-amber-400",
    description: "Full-featured e-commerce application supporting multi-vendor management, seamless payments, inventory tracking, and a stunning storefront built for scale and conversion.",
    longDescription: "Launch your online store with Shrote's feature-rich E-Commerce Application. Designed for scalability and performance, our platform supports everything from single-brand stores to complex multi-vendor marketplaces.",
    features: ["Multi-Vendor Support", "Payment Gateway", "Smart Inventory", "Mobile Commerce", "Order Management", "Customer Reviews", "Discount Engine", "Analytics Dashboard"],
    benefits: ["Launch store in days", "99.9% uptime", "SEO-optimized storefront", "Multi-payment support", "Real-time inventory sync", "Abandoned cart recovery"],
    techStack: ["Next.js", "Stripe", "Razorpay", "Node.js", "PostgreSQL", "Redis"],
    keywords: "e-commerce app development India, online store software, multi-vendor marketplace, e-commerce platform Bangalore, shopping cart software",
  },
  {
    slug: "accounting-software",
    name: "Accounting Software",
    tagline: "Smart Financial Management",
    category: "Finance",
    tag: "Enterprise",
    gradient: "from-emerald-600 to-green-400",
    description: "Comprehensive accounting software enabling businesses to manage ledgers, invoicing, GST/tax compliance, financial reports, and cash flows with unmatched accuracy.",
    longDescription: "Shrote's Accounting Software simplifies complex financial operations with an intuitive interface. From automated invoicing to GST compliance, our software ensures your finances are always accurate and up-to-date.",
    features: ["GST & Tax Filing", "Invoice Generation", "P&L Reports", "Bank Reconciliation", "Multi-currency", "Expense Tracking", "Audit Trail", "Financial Dashboards"],
    benefits: ["100% GST compliant", "Automated tax calculations", "One-click financial reports", "Bank feed integration", "Multi-branch accounting", "Role-based access"],
    techStack: ["React", "Node.js", "PostgreSQL", "Chart.js", "PDF Generation", "AWS"],
    keywords: "accounting software India, GST billing software, financial management software, bookkeeping software Bangalore, tax compliance software",
  },
  {
    slug: "payroll-software",
    name: "Payroll Software",
    tagline: "Automated Salary & Compliance",
    category: "HR & Workforce",
    tag: "Automation",
    gradient: "from-sky-600 to-blue-400",
    description: "End-to-end payroll automation covering salary computation, tax deductions, PF/ESI compliance, payslip generation, and direct bank disbursement.",
    longDescription: "Automate your entire payroll process with Shrote's Payroll Software. From salary computation to compliance filing, everything is handled automatically with zero errors.",
    features: ["Auto Salary Calc", "PF/ESI Compliance", "Payslip Generation", "Bank Integration", "Tax Deductions", "Loan Management", "Overtime Calculation", "Year-end Processing"],
    benefits: ["Zero payroll errors", "Compliance-ready", "One-click payslips", "Direct bank transfers", "Employee self-service", "Multi-pay structure support"],
    techStack: ["React", "Node.js", "PostgreSQL", "Banking APIs", "PDF Generation"],
    keywords: "payroll software India, salary management system, PF ESI compliance software, automated payroll Bangalore, payslip generation software",
  },
  {
    slug: "ai-agents",
    name: "AI Agents",
    tagline: "Intelligent Automation Agents",
    category: "Artificial Intelligence",
    tag: "AI-Powered",
    gradient: "from-fuchsia-600 to-pink-500",
    description: "Deploy intelligent AI agents that autonomously handle complex business workflows — from data analysis to decision automation — powered by cutting-edge large language models.",
    longDescription: "Shrote's AI Agents are autonomous software entities that understand, reason, and act on your behalf. Powered by state-of-the-art LLMs and custom-trained models, they can automate complex workflows that previously required human intervention.",
    features: ["Workflow Automation", "NLP Processing", "Data Extraction", "Custom Training", "API Integration", "Decision Engine", "Continuous Learning", "Multi-tool Orchestration"],
    benefits: ["Automate 80% of repetitive tasks", "24/7 autonomous operation", "Custom-trained for your domain", "Seamless API integration", "Measurable ROI", "Scale without hiring"],
    techStack: ["Python", "LangChain", "OpenAI", "FastAPI", "Vector DBs", "Docker"],
    keywords: "AI agents development India, autonomous AI software, business automation AI, LLM integration, AI workflow automation Bangalore",
  },
  {
    slug: "ai-chatbot",
    name: "AI Chatbot",
    tagline: "24/7 Conversational AI",
    category: "Artificial Intelligence",
    tag: "AI-Powered",
    gradient: "from-teal-600 to-cyan-400",
    description: "Deploy smart AI chatbots on your website, apps, or WhatsApp. Handle customer queries, lead generation, support tickets, and sales conversations — automatically.",
    longDescription: "Shrote's AI Chatbot platform lets you deploy intelligent conversational agents across multiple channels. From your website to WhatsApp, our chatbots handle customer queries, generate leads, and provide 24/7 support with human-like conversations.",
    features: ["Multi-Platform", "Lead Capture", "Live Handover", "Analytics Dashboard", "WhatsApp Integration", "Custom Personality", "Multilingual Support", "Sentiment Analysis"],
    benefits: ["24/7 customer support", "Reduce support costs by 60%", "Increase lead conversion", "Seamless human handover", "Multi-language support", "Actionable analytics"],
    techStack: ["Python", "Dialogflow", "OpenAI", "Node.js", "WebSocket", "React"],
    keywords: "AI chatbot India, WhatsApp chatbot, customer service bot, conversational AI Bangalore, chatbot development company",
  },
  {
    slug: "health-monitoring-ai",
    name: "Health Monitoring AI",
    tagline: "AI Fitness & Health Tracker",
    category: "Health & Fitness",
    tag: "AI-Powered",
    gradient: "from-rose-600 to-red-400",
    description: "Advanced AI-driven health monitoring that tracks vitals, fitness metrics, sleep patterns, and offers personalized recommendations.",
    longDescription: "Shrote's Health Monitoring AI Solution combines wearable data integration with advanced machine learning to provide comprehensive health insights and personalized wellness recommendations.",
    features: ["Vital Tracking", "AI Health Insights", "Diet Planning", "Fitness Analytics", "Sleep Analysis", "Wearable Integration", "Health Reports", "Alert System"],
    benefits: ["Real-time health monitoring", "Personalized fitness plans", "Early anomaly detection", "Wearable device support", "Doctor-ready health reports", "Family health tracking"],
    techStack: ["React Native", "TensorFlow", "Python", "Firebase", "Bluetooth LE", "AWS"],
    keywords: "health monitoring app India, AI fitness tracker, health tracking software, wellness app development Bangalore, AI health solution",
  },
  {
    slug: "inventory-management",
    name: "Inventory Management",
    tagline: "Smart Stock Control System",
    category: "Operations",
    tag: "Enterprise",
    gradient: "from-yellow-600 to-amber-400",
    description: "Real-time inventory management for tracking stock levels, warehouse operations, supplier management, and auto-reorder.",
    longDescription: "Shrote's Inventory Management Software gives you complete visibility and control over your stock across multiple warehouses and locations. With automated reorder points and real-time tracking, you'll never face stockouts again.",
    features: ["Real-time Tracking", "Warehouse Mgmt", "Auto Reorder", "Barcode Support", "Multi-location", "Supplier Management", "Stock Alerts", "Purchase Orders"],
    benefits: ["Zero stockouts", "Real-time stock visibility", "Automated reordering", "Multi-warehouse support", "Barcode/QR scanning", "Detailed stock reports"],
    techStack: ["React", "Node.js", "PostgreSQL", "Redis", "Barcode APIs", "AWS"],
    keywords: "inventory management software India, stock tracking system, warehouse management, inventory control software Bangalore, stock management system",
  },
  {
    slug: "restaurant-management",
    name: "Restaurant Management",
    tagline: "Complete Restaurant OS",
    category: "Hospitality",
    tag: "Industry",
    gradient: "from-lime-600 to-green-500",
    description: "All-in-one restaurant management covering table reservations, order management, billing, kitchen display, menu management, and staff operations.",
    longDescription: "Shrote's Restaurant Management Software streamlines every aspect of your restaurant operations. From front-of-house table management to kitchen display systems and billing, everything works in perfect harmony.",
    features: ["Table Management", "KDS Integration", "Billing & POS", "Online Orders", "Menu Management", "Staff Scheduling", "Customer Feedback", "Multi-outlet Support"],
    benefits: ["30% faster table turnover", "Integrated POS system", "Online ordering support", "Real-time kitchen updates", "Staff performance tracking", "Customer loyalty programs"],
    techStack: ["React", "Node.js", "MongoDB", "Socket.IO", "Thermal Printing", "PWA"],
    keywords: "restaurant management software India, restaurant POS system, table management software, restaurant billing software Bangalore, food ordering system",
  },
  {
    slug: "book-shop-management",
    name: "Book Shop Management",
    tagline: "Modern Bookstore Solution",
    category: "Retail",
    tag: "Industry",
    gradient: "from-indigo-600 to-blue-500",
    description: "Comprehensive bookstore management with catalogue management, ISBN tracking, point of sale, online storefront integration, and customer loyalty programs.",
    longDescription: "Shrote's Book Shop Management Software is designed specifically for bookstores. Manage your entire catalogue, track inventory by ISBN, process sales, and build customer loyalty — all from one platform.",
    features: ["ISBN Tracking", "POS System", "Online Store Sync", "Loyalty Program", "Catalogue Management", "Publisher Database", "Order Management", "Sales Reports"],
    benefits: ["ISBN-based inventory", "Integrated POS", "Online-offline sync", "Customer loyalty tracking", "Publisher management", "Automated reordering"],
    techStack: ["React", "Node.js", "PostgreSQL", "Barcode APIs", "Stripe", "PWA"],
    keywords: "bookshop management software, bookstore POS system, book inventory software India, library management system, book shop billing software",
  },
  {
    slug: "ai-games",
    name: "AI Games",
    tagline: "Intelligent Game Experiences",
    category: "AI Gaming",
    tag: "AI-Powered",
    gradient: "from-purple-600 to-fuchsia-500",
    description: "Next-gen AI-powered gaming with adaptive difficulty, smart NPCs, procedural content, and personalized gameplay.",
    longDescription: "Shrote's AI Games division creates next-generation gaming experiences powered by artificial intelligence. Our games feature adaptive difficulty systems, intelligent NPCs, and procedurally generated content that ensures every playthrough is unique.",
    features: ["Adaptive AI NPCs", "Procedural Content", "Personalized Play", "Cross-Platform", "Real-time Multiplayer", "AI Storytelling", "Dynamic Difficulty", "Player Analytics"],
    benefits: ["Unique every playthrough", "AI-driven storytelling", "Cross-platform support", "Engaging progression", "Smart matchmaking", "Player behavior analytics"],
    techStack: ["Unity", "C#", "Python", "TensorFlow", "Firebase", "WebGL"],
    keywords: "AI games development, intelligent NPCs, procedural game generation, AI gaming company India, game development Bangalore",
  },
  {
    slug: "auto-booking-app",
    name: "Auto Booking App",
    tagline: "Smart Transport Booking Platform",
    category: "Transport",
    tag: "Industry",
    gradient: "from-cyan-600 to-sky-400",
    description: "Modern vehicle and cab booking app with real-time tracking, dynamic pricing, driver management, and seamless payment.",
    longDescription: "Shrote's Auto Booking App is a complete transport booking solution for ride-hailing businesses, fleet operators, and cab services. With real-time GPS tracking, dynamic pricing algorithms, and seamless payment integration.",
    features: ["Real-time Tracking", "Driver Management", "Dynamic Pricing", "Digital Payments", "Route Optimization", "Ride History", "Rating System", "Admin Dashboard"],
    benefits: ["Real-time GPS tracking", "Automated fare calculation", "Multiple payment options", "Driver performance tracking", "Route optimization", "Comprehensive analytics"],
    techStack: ["React Native", "Node.js", "Google Maps API", "Razorpay", "Firebase", "Socket.IO"],
    keywords: "cab booking app development, ride hailing software India, auto booking app, transport booking platform Bangalore, fleet management app",
  },
  {
    slug: "gift-shop-management",
    name: "Gift Shop Management",
    tagline: "Complete Gift Retail Solution",
    category: "Retail",
    tag: "Industry",
    gradient: "from-pink-600 to-rose-400",
    description: "Tailored gift shop management with catalogue, custom order handling, seasonal promotions, inventory, POS billing, and CRM.",
    longDescription: "Shrote's Gift Shop Management Software handles every aspect of running a gift shop — from managing your product catalogue and processing custom orders to running seasonal promotions and tracking customer preferences.",
    features: ["Custom Orders", "Seasonal Promos", "POS & Billing", "CRM Integration", "Gift Wrapping Options", "Catalogue Management", "Customer Wishlists", "Sales Analytics"],
    benefits: ["Manage custom orders easily", "Seasonal promotion engine", "Customer preference tracking", "Integrated POS billing", "Gift wrapping management", "Sales trend analysis"],
    techStack: ["React", "Node.js", "MongoDB", "Stripe", "Thermal Printing", "PWA"],
    keywords: "gift shop management software, gift store POS, retail management system India, gift shop billing software, custom order management",
  },
  {
    slug: "school-management",
    name: "School Management",
    tagline: "Complete EdTech Platform",
    category: "Education",
    tag: "Enterprise",
    gradient: "from-blue-700 to-indigo-500",
    description: "All-in-one school management handling admissions, attendance, timetables, fee collection, examinations, parent communication, and performance analytics.",
    longDescription: "Shrote's School Management Software digitizes and automates every aspect of school administration. From student admissions and fee management to examination systems and parent communication — everything is managed from a single, intuitive platform.",
    features: ["Admission Mgmt", "Fee Collection", "Exam Portal", "Parent App", "Timetable Generator", "Transport Tracking", "Library Management", "Staff Management"],
    benefits: ["Paperless administration", "Online fee collection", "Automated report cards", "Parent-teacher communication", "Transport tracking", "Comprehensive analytics"],
    techStack: ["React", "Node.js", "PostgreSQL", "React Native", "Firebase", "AWS"],
    keywords: "school management software India, school ERP system, student management system, fee management software Bangalore, school administration software",
  },
  {
    slug: "studio-management",
    name: "Studio Management",
    tagline: "Photography & Studio OS",
    category: "Creative",
    tag: "Industry",
    gradient: "from-gray-600 to-slate-500",
    description: "Professional studio management for photographers and videographers — booking management, client portals, delivery tracking, and invoice management.",
    longDescription: "Shrote's Studio Management Software is built specifically for photography and videography studios. Manage bookings, track shoots, deliver galleries to clients, and handle invoicing — all from one beautiful platform.",
    features: ["Session Booking", "Client Portal", "Delivery Tracking", "Invoice & Billing", "Gallery Management", "Calendar Sync", "Contract Management", "Revenue Reports"],
    benefits: ["Streamlined bookings", "Client self-service portal", "Online gallery delivery", "Automated invoicing", "Calendar integration", "Revenue tracking"],
    techStack: ["React", "Node.js", "PostgreSQL", "Cloudinary", "Stripe", "Google Calendar API"],
    keywords: "studio management software, photography studio software India, photographer booking system, studio billing software Bangalore, photography business management",
  },
];

export const services = [
  {
    slug: "web-development",
    name: "Web Development",
    tagline: "Enterprise-Grade Web Solutions",
    gradient: "from-blue-600 to-cyan-500",
    description: "We build fast, responsive, SEO-optimized websites and web applications using React, Next.js, Node.js, and modern frameworks — tailored for enterprise scale and performance.",
    longDescription: "Shrote Technology's web development service delivers cutting-edge websites and web applications that drive business growth. We specialize in React, Next.js, and Node.js ecosystems, building everything from corporate websites to complex SaaS platforms. Every project is crafted with SEO best practices, responsive design, and performance optimization at its core.",
    features: ["React & Next.js", "Progressive Web Apps", "Custom CMS", "API Development", "E-commerce Platforms", "Dashboard Applications", "Landing Pages", "Web Portals"],
    benefits: ["SEO-optimized from day one", "Lightning-fast performance", "Mobile-first responsive design", "Scalable architecture", "Clean, maintainable code", "Post-launch support"],
    techStack: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "Tailwind CSS", "AWS", "Vercel"],
    keywords: "web development company Bangalore, website development India, React development services, Next.js development company, custom web application development",
  },
  {
    slug: "ai-agent-development",
    name: "AI Agent Development",
    tagline: "Autonomous AI Solutions",
    gradient: "from-fuchsia-600 to-pink-500",
    description: "We design and deploy custom AI agents powered by LLMs that automate workflows, extract insights, handle complex reasoning tasks, and seamlessly integrate into your systems.",
    longDescription: "Our AI Agent Development service builds intelligent autonomous agents that revolutionize how your business operates. Leveraging cutting-edge LLMs, RAG pipelines, and tool-calling architectures, we create agents that understand context, make decisions, and execute multi-step workflows without human intervention.",
    features: ["LLM Integration", "RAG Pipelines", "Tool Calling", "Custom Fine-tuning", "Multi-agent Systems", "Knowledge Graphs", "Conversation Memory", "API Orchestration"],
    benefits: ["Automate complex workflows", "24/7 intelligent processing", "Custom-trained for your domain", "Measurable productivity gains", "Continuous improvement", "Seamless integration"],
    techStack: ["Python", "LangChain", "OpenAI", "Claude", "FastAPI", "Vector DBs", "Docker", "Kubernetes"],
    keywords: "AI agent development India, LLM integration services, custom AI agents Bangalore, AI automation company, artificial intelligence development services",
  },
  {
    slug: "mobile-app-development",
    name: "Mobile App Development",
    tagline: "Cross-Platform & Native Apps",
    gradient: "from-green-500 to-emerald-400",
    description: "Cross-platform and native mobile app development for Android using React Native, Flutter, and Kotlin. From concept to Play Store launch — we handle the complete lifecycle.",
    longDescription: "Shrote Technology builds world-class mobile applications for Android and cross-platform deployment. Using React Native, Flutter, and native Kotlin/Java, we create high-performance apps that users love. From initial concept and UI/UX design to development, testing, and Play Store launch — we manage the entire app lifecycle.",
    features: ["React Native", "Flutter", "Kotlin/Java", "Play Store Launch", "UI/UX Design", "Push Notifications", "Offline Mode", "Analytics Integration"],
    benefits: ["Single codebase, multiple platforms", "Native-like performance", "Complete lifecycle management", "Play Store optimization", "Regular updates & maintenance", "Performance monitoring"],
    techStack: ["React Native", "Flutter", "Kotlin", "Firebase", "Redux", "REST APIs", "SQLite"],
    keywords: "mobile app development company India, Android app development Bangalore, React Native development, Flutter app development, custom mobile app development services",
  },
  {
    slug: "ios-app-development",
    name: "iOS App Development",
    tagline: "Premium Apple Ecosystem Apps",
    gradient: "from-gray-500 to-slate-400",
    description: "Premium iOS application development using Swift and SwiftUI. We create pixel-perfect, high-performance apps that meet Apple's design standards and App Store guidelines.",
    longDescription: "Our iOS development team specializes in creating premium applications for the Apple ecosystem. Using Swift and SwiftUI, we build apps that are not just functional but delightful to use. Every app we develop meets Apple's strict Human Interface Guidelines and App Store review requirements.",
    features: ["Swift & SwiftUI", "App Store Optimization", "Core Data", "Apple Design Guidelines", "ARKit Integration", "HealthKit", "Apple Pay", "Widget Support"],
    benefits: ["Apple design compliance", "App Store optimization", "Premium user experience", "High App Store ratings", "Security-first approach", "Ongoing maintenance"],
    techStack: ["Swift", "SwiftUI", "Xcode", "Core Data", "CloudKit", "TestFlight", "CI/CD"],
    keywords: "iOS app development India, iPhone app development Bangalore, Swift development company, SwiftUI app development, Apple app development services",
  },
  {
    slug: "iot-software-development",
    name: "IoT Software Development",
    tagline: "Connected Device Solutions",
    gradient: "from-orange-500 to-yellow-400",
    description: "End-to-end IoT software solutions — from device firmware and edge computing to cloud dashboards and real-time data analytics.",
    longDescription: "Shrote Technology provides comprehensive IoT software development services that connect your devices to intelligent cloud systems. From firmware development and edge computing to real-time dashboards and predictive analytics, we build the complete IoT stack.",
    features: ["Device Firmware", "Edge Computing", "Cloud Dashboards", "MQTT & Protocols", "Real-time Monitoring", "OTA Updates", "Device Management", "Predictive Analytics"],
    benefits: ["End-to-end IoT stack", "Real-time device monitoring", "Scalable cloud infrastructure", "Secure communication", "Predictive maintenance", "Custom dashboards"],
    techStack: ["Python", "C/C++", "MQTT", "AWS IoT", "Node.js", "React", "InfluxDB", "Grafana"],
    keywords: "IoT software development India, IoT solutions Bangalore, connected device software, IoT cloud platform, industrial IoT development company",
  },
  {
    slug: "digital-marketing",
    name: "Digital Marketing",
    tagline: "Data-Driven Growth Marketing",
    gradient: "from-amber-500 to-orange-400",
    description: "Comprehensive digital marketing services including SEO, SEM, social media marketing, content marketing, and analytics — all driven by data and focused on measurable ROI.",
    longDescription: "Shrote Technology's Digital Marketing services help businesses achieve measurable growth through data-driven strategies. We combine SEO expertise, paid advertising mastery, social media engagement, and content marketing to build your brand's online presence and drive qualified leads.",
    features: ["SEO & On-page Optimization", "Google Ads (SEM)", "Social Media Marketing", "Content Marketing", "Email Marketing", "Analytics & Reporting", "Brand Strategy", "Conversion Optimization"],
    benefits: ["Measurable ROI", "Higher search rankings", "Increased brand awareness", "Quality lead generation", "Data-driven decisions", "Multi-channel presence"],
    techStack: ["Google Analytics", "Google Ads", "Meta Business Suite", "SEMrush", "Ahrefs", "Mailchimp", "HubSpot"],
    keywords: "digital marketing company Bangalore, SEO services India, social media marketing, Google Ads management, content marketing agency, online marketing services",
  },
];
